language: generic
sudo: required # sudo permissions are required to run docker
services:
  - docker

before_install:
  - docker build -t ricardosandez/docker-react -f Dockerfile.dev .

script:
  # Set an env variable 'CI' to true so that 'npm run test' exits immmediately after executing. (See https://create-react-app.dev/docs/running-tests/#continuous-integration)
  # This must be an env variable in your system, it's not a flag of npm run test.
  # This is because Travis will not build if the result from running the tests is a code different from 0.
  - docker run -e CI=true ricardosandez/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-682978925964'
  bucker_path: 'docker-react' # path inside the bucket where our app data is stored. Usually the same as the app name.
  on:
    branch: main # deploy to aws every time main receives new code 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
